import { onDocumentCreated, onDocumentUpdated } from "firebase-functions/v2/firestore";
import { setGlobalOptions } from "firebase-functions/v2";
import * as admin from "firebase-admin";

admin.initializeApp();
setGlobalOptions({ region: "us-central1" });

async function sendToUser(userId: string, title: string, body: string) {
  const db = admin.firestore();

  const snap = await db
    .collection("pushTokens")
    .where("userId", "==", userId)
    .get();

  if (snap.empty) {
    console.log("Nenhum token encontrado para o usuário:", userId);
    return;
  }

  const tokens: string[] = snap.docs
    .map((doc) => doc.data().token)
    .filter((token): token is string => typeof token === "string" && token.length > 0);

  if (!tokens.length) {
    console.log("Nenhum token válido encontrado para o usuário:", userId);
    return;
  }

  const message = {
    notification: {
      title,
      body,
    },
    webpush: {
      notification: {
        icon: "/icons/icon-192.png",
        badge: "/icons/icon-192.png",
      },
    },
    tokens,
  };

  const response = await admin.messaging().sendEachForMulticast(message);

  console.log("Notificações enviadas:", response.successCount);
  console.log("Falhas:", response.failureCount);

  // Remove tokens inválidos
  const invalidCodes = new Set([
    "messaging/invalid-registration-token",
    "messaging/registration-token-not-registered",
  ]);

  const batch = db.batch();

  response.responses.forEach((r, index) => {
    if (!r.success && r.error && invalidCodes.has(r.error.code)) {
      const token = tokens[index];
      snap.docs.forEach((docSnap) => {
        if (docSnap.data().token === token) {
          batch.delete(docSnap.ref);
        }
      });
    }
  });

  await batch.commit();
}

export const onBillCreated = onDocumentCreated("bills/{billId}", async (event) => {
  const data = event.data?.data();
  if (!data) return;

  const userId = data.userId;
  const name = data.name || "Conta";
  const dueDate = data.dueDate || "";
  const autoGenerated = Boolean(data.autoGenerated);

  if (!userId) return;

  const title = autoGenerated ? "Conta recorrente criada" : "Nova conta criada";
  const body = `${name} foi registrada${dueDate ? ` com vencimento em ${dueDate}` : ""}.`;

  await sendToUser(userId, title, body);
});

export const onTransactionCreated = onDocumentCreated(
  "transactions/{transactionId}",
  async (event) => {
    const data = event.data?.data();
    if (!data) return;

    const userId = data.userId;
    const category = data.category || "Gasto";
    const value = Number(data.value || 0);
    const autoGenerated = Boolean(data.autoGenerated);

    if (!userId) return;

    const title = autoGenerated ? "Gasto recorrente lançado" : "Novo gasto lançado";
    const body = `${category} no valor de R$ ${value.toFixed(2)}.`;

    await sendToUser(userId, title, body);
  }
);

export const onBillPaid = onDocumentUpdated("bills/{billId}", async (event) => {
  const before = event.data?.before.data();
  const after = event.data?.after.data();

  if (!before || !after) return;

  const beforeStatus = before.status;
  const afterStatus = after.status;
  const userId = after.userId;
  const name = after.name || "Conta";
  const paidBy = after.paidBy || "alguém";

  if (!userId) return;

  if (beforeStatus !== "paga" && afterStatus === "paga") {
    await sendToUser(userId, "Conta paga", `${name} foi marcada como paga por ${paidBy}.`);
  }
});